### ISSUE TITLE
В некоторых случаях родительский комментарий имеет полосу прокрутки

### ISSUE THREAD

**Issue by dartraiden** [Inversion-des/Habrahabr--Answer-to#9]
Пример комментария: https://habr.com/post/408671/#comment_18481605
Если родительский комментарий (в котором цитата + ответ на нее) за пределами экрана, то он показывается нормально.
Если же он виден частично, вот так:

![default](https://user-images.githubusercontent.com/5046855/42377204-056d467e-812b-11e8-8779-be881e0ca88f.png)

(то есть, цитируемая часть ушла за пределы экрана), то юзерскрипт покажет его с полосой вертикальной прокрутки:

![2](https://user-images.githubusercontent.com/5046855/42377178-e57e074a-812a-11e8-830a-a2cedd9aa47d.png)

**Comment by Inversion-des** [comment]
Это не баг, это фича ) 

Оно старается показать предыдущий комент так, чтобы не накрыть текущий, на котором находится курсор. 

Если хочется видеть больше того родительского комента, то просто нужно немного проскролить страницу так чтобы текущий комментарий был на середине экрана, или немного ниже середины, если родительский очень большой.

Полоса прокрутки здесь служит просто индикатором что всё не влезло, воспользоваться ею невозможно.

**Comment by dartraiden** [comment]
Вот оно что, Михалыч... (с) :)
